config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: "users/sessions" }
  root to: "games#new"

  resources :games, only: [:new, :create, :edit, :update] do
    resources :players, only: [:index, :new, :create, :edit, :update]
    resource :scorecard, only: [:show, :create]
  end
end

app/models/player.rb
class Player < ActiveRecord::Base
  belongs_to :game
  has_many :scores
  has_many :rounds, through: :scores

  def total_score
    Score.total_score(self)
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

  def index
    @game = Game.find(params[:game_id])
    @players = @game.players
  end

  def new
    @game = Game.find(params[:game_id])
    @player = Player.new
  end

  def create
    player = Player.create(new_player_params)
    redirect_to game_players_path(game_id: params[:game_id])
  end

  def edit
    @game = Game.find(params[:game_id])
    @player = Player.find(params[:id])
  end

  def update
    player = Player.find(params[:id])
    if player.update_attributes(player_params)
      flash[:notice] = "Player Updated"
      redirect_to game_players_path(game_id: params[:game_id])
    else
      flash[:alert] = "Problem Saving Player"
    end
  end

  private
  def player_params
    params.require(:player).permit(:name)
  end

  def new_player_params
    player_params.merge(game_id: params[:game_id])
  end
end

app/views/players/_player.html.erb
<%= form_for [@game, @player] do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>
  <%= form.submit "Submit" %>
<% end %>

app/views/players/edit.html.erb
<%= render @player %>

app/views/players/index.html.erb
<h1><%= link_to @game.name, edit_game_path(@game) %></h1>

<%= link_to "Add a Player", new_game_player_path %>

<ul class="players">
  <% @players.each do |player| %>
    <li><%= link_to player.name, edit_game_player_path(@game, player) %></li>
  <% end %>
</ul>

<%= button_to "Start Game", game_scorecard_path, method: 'get' %>

app/views/players/new.html.erb
<%= render @player %>